FROM node:alpine as build

COPY package.json package.json
RUN npm install
COPY . .
RUN npx next build

FROM nginx:stable-alpine

COPY --from=build /build /usr/share/nginx/html
COPY --from=build nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3900

CMD [ "nginx", "-g", "deamon off" ]