version: "3.9"

networks:
  password:

services:
  nginx: 
    image: nginx:stable-alpine
    restart: always
    ports:
      - "1900:80"
    volumes:
        - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - password

  backend: 
    build:
      context: ./backend
    restart: always
    networks:
      - password

  frontend: 
    build:
      context: ./frontend
    restart: always
    networks:
      - password