import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import styles from './main.module.css'
const ubuntu = Ubuntu({ weight: "400", subsets: ["latin", "cyrillic"] });

export const metadata: Metadata = {
  title: "Generator Password",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={ubuntu.className}>
      <body className={styles.body}>{children}</body>
    </html>
  );
}
